import React, { useState } from 'react';
import Icon from './Icon';
import GlossaryTooltip from './GlossaryTooltip';

export default function NarrativePanel({ narrative, isAiGenerated, missingApiKey }) {
  const [collapsed, setCollapsed] = useState(false);
  const [copied, setCopied] = useState(false);

  if (missingApiKey) {
    return (
      <div className="w-full bg-surface-container-lowest border-l-4 border-outline/20 p-5 rounded-r-lg mb-4 flex items-center justify-center">
        <span className="text-tertiary text-[13px] text-center max-w-sm">
          Enter your Anthropic API key in the AI Assistant panel to enable AI-generated business insights.
        </span>
      </div>
    );
  }

  if (!narrative) return null;

  const handleCopy = () => {
    const textToCopy = `${narrative.headline}\n\n${narrative.context}\n\nEstimated Impact: ${narrative.impact}\n\nRecommended Action: ${narrative.action}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };


  return (
    <div className="w-full bg-surface-container-lowest border-l-4 border-primary rounded-r-lg mb-4 shadow-sm overflow-hidden transition-all duration-250 ease-in-out">
      <div className="p-4 md:px-6 md:py-5">
        
        {/* Headline Row */}
        <div className="flex items-start justify-between gap-4">
          <h3 className="text-[15px] font-semibold text-primary leading-snug flex-1">
            {narrative.headline}
          </h3>
          <button 
            onClick={() => setCollapsed(!collapsed)}
            className="text-[12px] text-secondary hover:text-primary whitespace-nowrap mt-0.5"
          >
            {collapsed ? 'Show more' : 'Hide'}
          </button>
        </div>

        {/* Collapsible Content */}
        {!collapsed && (
          <div className="mt-4 space-y-4 animate-in fade-in slide-in-from-top-2 duration-300">
            <p className="text-[14px] font-normal text-on-surface line-height-[1.65]">
              <GlossaryTooltip text={narrative.context} />
            </p>
            
            {narrative.impact && narrative.impact !== 'Not calculable' && (
              <p className="text-[14px] font-normal text-on-surface line-height-[1.65]">
                <span className="inline-block text-[12px] font-semibold uppercase tracking-[0.04em] text-secondary mr-2">
                  Estimated Impact
                </span>
                <GlossaryTooltip text={narrative.impact} />
              </p>
            )}
            
            {narrative.action && (
              <p className="text-[14px] font-normal text-on-surface line-height-[1.65]">
                <span className="inline-block text-[12px] font-semibold uppercase tracking-[0.04em] text-secondary mr-2">
                  Recommended Action
                </span>
                <span className="font-medium"><GlossaryTooltip text={narrative.action} /></span>
              </p>
            )}
            
            {/* Footer */}
            <div className="pt-3 mt-3 border-t border-outline/10 flex items-center justify-end gap-4">
              {isAiGenerated && (
                <span className="text-[12px] text-tertiary flex items-center gap-1">
                  <Icon name="auto_awesome" size={14} /> Insight generated by AI
                </span>
              )}
              <button 
                onClick={handleCopy}
                className="text-[12px] text-secondary hover:text-on-surface flex items-center gap-1 font-medium transition-colors"
              >
                {copied ? (
                  <><Icon name="check" size={14} className="text-secondary" /> Copied</>
                ) : (
                  <><Icon name="content_copy" size={14} /> Copy Narrative</>
                )}
              </button>
            </div>
          </div>
        )}
        
      </div>
    </div>
  );
}
